default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: desafio-backend

development:
  <<: *default
  database: desafio_backend_development

test:
  <<: *default
  database: desafio_backend_test

production:
  <<: *default
  database: desafio_backend_production
